
name: Generate skopeo packages

on:
  push:
    branches:
      - test

env:
  REPOSITORY_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.ref_name }}

concurrency:
  group: publish.${{ github.ref || github.run_id }}.${{ github.event_name }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Build
        run:  | 
          docker build -f Dockerfile -t skopeo-build .
          docker run -v ./bin:/skopeo/bin -t skopeo-build
        shell: bash
      - name: Build
        run:  | 
          ls -la ./bin
        shell: bash
      # - name: Upload release attachment
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run:  | 
      #     gh release upload ${{ github.ref_name }} bin/skopeo.linux.amd64 #skopeo.linux.amd64
      #     gh release upload ${{ github.ref_name }} bin/skopeo.linux.arm64 #skopeo.linux.arm64
      #     gh release upload ${{ github.ref_name }} bin/skopeo.darwin.amd64 #skopeo.darwin.amd64
      #     gh release upload ${{ github.ref_name }} bin/skopeo.darwin.arm64 #skopeo.darwin.arm64
      #     gh release upload ${{ github.ref_name }} bin/skopeo.windows.amd64.exe #skopeo.windows.amd64.exe
      #     gh release upload ${{ github.ref_name }} bin/skopeo.windows.arm64.exe #skopeo.windows.arm64.exe
      #   shell: bash
