
name: Release Python Library

# on:
#   release:
#     types:
#       - published
#       - edited
on:
  push:
    branches:
      - build

env:
  REPOSITORY_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.ref_name }}

concurrency:
  group: publish.${{ github.ref || github.run_id }}.${{ github.event_name }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt-get update
          sudo apt install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config
          make bin/skopeo.linux.amd64
          make bin/skopeo.linux.arm64
          make bin/skopeo.windows.amd64
          make bin/skopeo.windows.arm64
          make bin/skopeo.darwin.amd64
          make bin/skopeo.darwin.arm64
        shell: bash

      - name: dir
        run: |
          ls -la ./bin
        shell: bash