
name: Release Python Library

# on:
#   release:
#     types:
#       - published
#       - edited
on:
  push:
    branches:
      - build

env:
  REPOSITORY_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.ref_name }}

concurrency:
  group: publish.${{ github.ref || github.run_id }}.${{ github.event_name }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt-get update
          sudo apt install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config
          make bin/skopeo.linux.amd64
          make bin/skopeo.linux.arm64
          make bin/skopeo.darwin.amd64
          make bin/skopeo.darwin.arm64
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: skopeo-linux-build
          path: bin
  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          brew install gpgme
          make bin/skopeo.darwin.amd64
          make bin/skopeo.darwin.arm64
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: skopeo-mac-build
          path: bin